server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: market-price-raw-listener-group
      auto-offset-reset: latest
    topic: market.prices.raw
    streams:
      application-id: market-state-service

#    admin:
#      properties:
#        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094